using System.Text;
using VanEngine.Game.Architecture;

namespace VanEngine.Game.Core;

public static class ReportGenerator
{
    public static string GenerateMarkdownReport(SovereignState state)
    {
        var sb = new StringBuilder();
        var res = state.Resources;

        sb.AppendLine("# Oera Linda Simulator — Project Health Report");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"**Year:** {state.Year}");
        sb.AppendLine();
        sb.AppendLine("## Sovereignty");
        sb.AppendLine();
        sb.AppendLine($"| Metric | Value |");
        sb.AppendLine($"|--------|-------|");
        sb.AppendLine($"| Sovereignty | {state.Sovereignty:F1}% |");
        sb.AppendLine($"| Language Purity | {state.LanguagePurity:F1}% |");
        sb.AppendLine($"| Total Compliant Lines | {state.TotalCompliantLines} |");
        sb.AppendLine();
        sb.AppendLine("## Resource Ledger");
        sb.AppendLine();
        sb.AppendLine($"| Resource | Amount |");
        sb.AppendLine($"|----------|--------|");
        sb.AppendLine($"| Food | {res.Food} |");
        sb.AppendLine($"| Wood | {res.Wood} |");
        sb.AppendLine($"| Stone | {res.Stone} |");
        sb.AppendLine($"| Metal | {res.Metal} |");
        sb.AppendLine($"| Wealth | {res.Wealth} |");
        sb.AppendLine($"| Gold | {res.Gold} |");
        sb.AppendLine();
        sb.AppendLine("## Citizen Roster");
        sb.AppendLine();
        sb.AppendLine($"| Name | Files | Role | Homeless | XP | Specialization |");
        sb.AppendLine($"|------|-------|------|----------|-----|---------------|");
        foreach (var c in state.Citizens)
        {
            string role = c.RoleType switch
            {
                1 => "Builder", 2 => "Guardian", 3 => "Scribe",
                4 => "Merchant", 5 => "Elder", 6 => "Archivist",
                7 => "Sentinel", 8 => "Jurist", _ => "Citizen",
            };
            sb.AppendLine($"| {c.Name} | {c.OwnedFiles.Count} | {role} | {c.IsHomeless} | {c.XP} | {c.Specialization} |");
        }
        sb.AppendLine();
        sb.AppendLine("## Houses");
        sb.AppendLine();
        sb.AppendLine($"| Name | Namespace | Tier | State | Files | Errors |");
        sb.AppendLine($"|------|-----------|------|-------|-------|--------|");
        foreach (var h in state.Houses)
        {
            int errs = h.TrackedFiles.Sum(f => f.ErrorCount);
            sb.AppendLine($"| {h.ProjectName} | {h.RootNamespace} | {h.Tier} | {h.CurrentState} | {h.TrackedFiles.Count} | {errs} |");
        }
        sb.AppendLine();
        sb.AppendLine("## Year-over-Year Sovereignty");
        sb.AppendLine();
        var timeline = state.GetTimeline().Where(t => t.EventType == "event" || t.EventType == "house").ToList();
        var byYear = timeline.GroupBy(t => t.Year).OrderBy(g => g.Key);
        sb.AppendLine("| Year | Events |");
        sb.AppendLine("|------|--------|");
        foreach (var g in byYear)
            sb.AppendLine($"| {g.Key} | {g.Count()} |");
        sb.AppendLine();
        sb.AppendLine("## Directive Violations");
        sb.AppendLine();
        var weights = state.GetDirectiveWeights();
        foreach (var kvp in weights)
        {
            int violationCount = state.UploadHistory
                .Where(u => u.Details != null && u.Details.Contains(kvp.Key, StringComparison.OrdinalIgnoreCase))
                .Count();
            sb.AppendLine($"- **{kvp.Key}**: weight {kvp.Value:F1}, {violationCount} violations");
        }
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine($"*Report generated by Oera Linda Simulator v1.0*");

        return sb.ToString();
    }

    public static string GenerateHtmlReport(SovereignState state)
    {
        var md = GenerateMarkdownReport(state);
        var sb = new StringBuilder();

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head><meta charset=\"UTF-8\">");
        sb.AppendLine("<title>Oera Linda Simulator — Project Health Report</title>");
        sb.AppendLine("<style>");
        sb.AppendLine("body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; ");
        sb.AppendLine("       background: #0e1017; color: #d2d6df; max-width: 900px; margin: 0 auto; padding: 2em; }");
        sb.AppendLine("h1 { color: #f0c040; border-bottom: 2px solid #3a3f4a; padding-bottom: 0.3em; }");
        sb.AppendLine("h2 { color: #60a0ff; margin-top: 1.5em; }");
        sb.AppendLine("table { border-collapse: collapse; width: 100%; margin: 0.5em 0; }");
        sb.AppendLine("th, td { border: 1px solid #3a3f4a; padding: 6px 12px; text-align: left; }");
        sb.AppendLine("th { background: #1a1e28; color: #c0c8d8; }");
        sb.AppendLine("tr:nth-child(even) { background: #13161f; }");
        sb.AppendLine(".sovereignty { font-size: 2em; font-weight: bold; color: ");
        sb.AppendLine(state.Sovereignty >= 70 ? "#00dc8c" : state.Sovereignty >= 40 ? "#f0c040" : "#f04646");
        sb.AppendLine("; }");
        sb.AppendLine(".footer { margin-top: 3em; font-size: 0.8em; color: #6a7080; text-align: center; }");
        sb.AppendLine("</style>");
        sb.AppendLine("</head><body>");

        sb.AppendLine("<h1>Oera Linda Simulator &mdash; Project Health Report</h1>");
        sb.AppendLine($"<p><strong>Generated:</strong> {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
        sb.AppendLine($"<p><strong>Year:</strong> {state.Year}</p>");

        sb.AppendLine("<h2>Sovereignty</h2>");
        sb.AppendLine($"<div class=\"sovereignty\">{state.Sovereignty:F1}%</div>");
        sb.AppendLine($"<p>Language Purity: {state.LanguagePurity:F1}% &bull; ");
        sb.AppendLine($"Total Compliant Lines: {state.TotalCompliantLines}</p>");

        sb.AppendLine("<h2>Resource Ledger</h2>");
        sb.AppendLine("<table><tr><th>Resource</th><th>Amount</th></tr>");
        var res = state.Resources;
        sb.AppendLine($"<tr><td>Food</td><td>{res.Food}</td></tr>");
        sb.AppendLine($"<tr><td>Wood</td><td>{res.Wood}</td></tr>");
        sb.AppendLine($"<tr><td>Stone</td><td>{res.Stone}</td></tr>");
        sb.AppendLine($"<tr><td>Metal</td><td>{res.Metal}</td></tr>");
        sb.AppendLine($"<tr><td>Wealth</td><td>{res.Wealth}</td></tr>");
        sb.AppendLine($"<tr><td>Gold</td><td>{res.Gold}</td></tr>");
        sb.AppendLine("</table>");

        sb.AppendLine("<h2>Citizen Roster</h2>");
        sb.AppendLine("<table><tr><th>Name</th><th>Files</th><th>Role</th><th>XP</th><th>Specialization</th></tr>");
        foreach (var c in state.Citizens)
        {
            string role = c.RoleType switch
            {
                1 => "Builder", 2 => "Guardian", 3 => "Scribe",
                4 => "Merchant", 5 => "Elder", 6 => "Archivist",
                7 => "Sentinel", 8 => "Jurist", _ => "Citizen",
            };
            sb.AppendLine($"<tr><td>{c.Name}</td><td>{c.OwnedFiles.Count}</td><td>{role}</td><td>{c.XP}</td><td>{c.Specialization}</td></tr>");
        }
        sb.AppendLine("</table>");

        sb.AppendLine("<h2>Houses</h2>");
        sb.AppendLine("<table><tr><th>Name</th><th>Namespace</th><th>Tier</th><th>State</th><th>Files</th><th>Errors</th></tr>");
        foreach (var h in state.Houses)
        {
            int errs = h.TrackedFiles.Sum(f => f.ErrorCount);
            sb.AppendLine($"<tr><td>{h.ProjectName}</td><td>{h.RootNamespace}</td><td>{h.Tier}</td><td>{h.CurrentState}</td><td>{h.TrackedFiles.Count}</td><td>{errs}</td></tr>");
        }
        sb.AppendLine("</table>");

        sb.AppendLine("<h2>Year-over-Year Activity</h2>");
        sb.AppendLine("<table><tr><th>Year</th><th>Events</th></tr>");
        var timeline = state.GetTimeline().Where(t => t.EventType == "event" || t.EventType == "house").ToList();
        var byYear = timeline.GroupBy(t => t.Year).OrderBy(g => g.Key);
        foreach (var g in byYear)
            sb.AppendLine($"<tr><td>{g.Key}</td><td>{g.Count()}</td></tr>");
        sb.AppendLine("</table>");

        sb.AppendLine("<h2>Directive Violations</h2>");
        sb.AppendLine("<table><tr><th>Pattern</th><th>Weight</th><th>Violations</th></tr>");
        var weights = state.GetDirectiveWeights();
        foreach (var kvp in weights)
        {
            int vc = state.UploadHistory
                .Where(u => u.Details != null && u.Details.Contains(kvp.Key, StringComparison.OrdinalIgnoreCase))
                .Count();
            sb.AppendLine($"<tr><td>{kvp.Key}</td><td>{kvp.Value:F1}</td><td>{vc}</td></tr>");
        }
        sb.AppendLine("</table>");

        sb.AppendLine("<div class=\"footer\">Report generated by Oera Linda Simulator v1.0</div>");
        sb.AppendLine("</body></html>");

        return sb.ToString();
    }

    public static void SaveMarkdownReport(SovereignState state, string filePath)
    {
        File.WriteAllText(filePath, GenerateMarkdownReport(state));
    }

    public static void SaveHtmlReport(SovereignState state, string filePath)
    {
        File.WriteAllText(filePath, GenerateHtmlReport(state));
    }

    public static string GetDefaultReportPath(string extension = "md")
    {
        var dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "reports");
        Directory.CreateDirectory(dir);
        return Path.Combine(dir, $"health_report_{DateTime.Now:yyyyMMdd_HHmmss}.{extension}");
    }
}
